sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: aitem:kfjTXFxdFQxyBbAJ0UtYVqOe
deploy:
  app: vast-cove-62697
  provider: heroku
  api_key:
    secure: hie1GDmIFKM4WB0ZkqliAunHXbxym/FnXpIIdiiwpYQebpxveONN0bj3L+f6vP5ziAdKAkVWrGgdUNH57RFeL/+BbpvN3VOF5l8ZoSExDTQ6f7yW0UvlBhfJYUcvclF3MVKmQedjj/5CATamvUIowg/NfGiYevkgVHzjeA6sfMWwm1uQx/WQlbshvwU+jG4ysJMIDeDMcJTPiWyUyUmQr3epPTs1+HyTpYimasCw21JMHSY881QO6mwzjV3clk4rUl+vKKUWro9CIOfeS382fFu6N3n9hmQ3i4V24iqR3OMSP37ESGGBUlqpuT2zB87CedW1rCHQ8oH0ulH/JzfgU/nso2YNt8GKr2R/jKWbQSHcxYO854Ue6xa0CLCBPp3npBALkm8+ksc0EUirN8xPLkmxUWPtzExfIl2GzFI4+HghwMH/o0yJyUS5HRvESLE/DJMrR4xjF1UOzN1i1/JcHADFkCYukYs8XMk/VxOFSLNJS10VWgLv5pBBYD42uvHtwGoRzA2vmk0ybBkR0iLvUYh272pNN61qDQpxkEHsz8sJdDocWX1q/bcDnVS3CFMEM727OLDj+bs6CQlvM+u4kAUm5gxNtYClrbX87unwqEV8lS7Cqdq10JaryAIJRIqlDcwNsv1d59P7YHLAd1BixahH7Vj01pE2Q8QF8SpIbJ4=
